/**
 * Reads the Vite-built single-file HTML apps from dist/ui/ and emits a
 * TypeScript source file that exports each as a string constant.
 *
 * Run between build:ui and build:server so tsc can compile the result.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIST_UI = join(ROOT, "dist", "ui");
const OUT_FILE = join(ROOT, "src", "generated", "ui-html.ts");

const tools = [
  { varName: "deIdentifyHtml", dir: "de-identify" },
  { varName: "reIdentifyHtml", dir: "re-identify" },
  { varName: "deIdentifyFileHtml", dir: "de-identify-file" },
] as const;

function escapeForTemplateLiteral(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

async function main() {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-ui-imports.ts — do not edit.",
    "",
  ];

  for (const { varName, dir } of tools) {
    const html = await readFile(join(DIST_UI, dir, "mcp-app.html"), "utf-8");
    lines.push(`export const ${varName} = \`${escapeForTemplateLiteral(html)}\`;`);
    lines.push("");
  }

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, lines.join("\n"));
  console.log(`Generated ${OUT_FILE}`);
}

main();
